SVConfig = {}

SVConfig.Webhooks = {
    Bans = "https://discord.com/api/webhooks/1073642724110110820/2XBna0tzGAAJJ4JDlv9Ir3DWEP9UIr8_gP_dgQv0I-LCRtVz7bFVZZxXYIUA0tAExeCS",
    Controls = "https://discord.com/api/webhooks/1073642850748743810/NNr-kvX3kcmb4fTn9DAQbzJAutPSeOFe1BK6EuRzeyzuf_MPy5zb4zibOESZadU0fg4L",
    Kicks = "https://discord.com/api/webhooks/1073642905736061000/wGV0m9TSaShd0DhRqpsvo_2OziqxXydU7TmHXf0n5YcyxRZq79wCQNqEIev5J95S7K9D",
    Warns = "https://discord.com/api/webhooks/1076609667783991296/8OlFvcVrpeURMT0ExhUFbng8XsORPw6cBUMOkdWZgkua275zNwwcG0Qwc-WsJfvfXHOI",
    ImageServer = "https://discord.com/api/webhooks/1073642953832145028/1BwmA9-cSJTnIWD9P3owF9Irt0tr0H59xul8r3ohg2JG-s5inOHlb3y0ftadRRNABxR6",
}

SVConfig.AntiServerEvents = true
SVConfig.ServerEvents = {
    'HCheat:TempDisableDetection',
    'BsCuff:Cuff696999',
    'adminmenu:allowall',
    'antilynx8r4a:anticheat',
    'antilynxr4:detect',
    'ynx8:anticheat',
    'lynx8:anticheat',
    'hentailover:xdlol',
    'antilynx8:anticheat',
    'antilynxr6:detection',
    'FAC:EzExec',
    'h:xd',
    'redst0nia:checking',
    'esx-qalle-hunting:sell',
    'trainheist:server:sellRewardItems',
    'trainheist:server:rewardItems',
}

SVConfig.EventsRate = true
SVConfig.RateTimer = 3000
SVConfig.EventsRated = {
    {name = "esx_illegal_drugs:startHarvestWeed", limit = 3},
    {name = "esx_drugs:pickedUpCannabis", limit = 3},
    {name = "esx_drugs:startHarvestWeed", limit = 3},
    {name = "esx_drugs:startHarvestCoke", limit = 3},
    {name = "esx_illegal_drugs:startHarvestCoke", limit = 3},
    {name = "esx_drugs:startHarvestMeth", limit = 3},
    {name = "esx_illegal_drugs:startHarvestMeth", limit = 3},
    {name = "esx_drugs:startHarvestOpium", limit = 3},
    {name = "esx_illegal_drugs:startHarvestOpium", limit = 3},
    {name = "esx_blanchisseur:startWhitening", limit = 3},
    {name = "esx_blanchisseur:washMoney", limit = 3},
    {name = "esx_blackmoney:washMoney", limit = 3},
    {name = "esx_moneywash:withdraw", limit = 3},
    {name = "laundry:washcash", limit = 3},
    {name = "esx_policejob:handcuff", limit = 5},
    {name = "esx_handcuffs:cuffing", limit = 5},
    {name = "gcPhone:_internalAddMessage", limit = 3},
    {name = "gcPhone:tchat_channel", limit = 3},
    {name = "js:jailuser", limit = 2},
    {name = "ljail:jailplayer", limit = 2},
    {name = "esx_jail:sendToJail", limit = 2},
    {name = "esx_jailer:sendToJail", limit = 2},
    {name = "esx-qalle-jail:jailPlayer", limit = 2},
    {name = "esx_fueldelivery:pay", limit = 2},
    {name = "esx_carthief:pay", limit = 2},
    {name = "esx_godirtyjob:pay", limit = 2},
    {name = "esx_pizza:pay", limit = 2},
    {name = "esx_ranger:pay", limit = 2},
    {name = "esx_garbagejob:pay", limit = 2},
    {name = "esx_slotmachine:sv:2", limit = 2},
    {name = "esx_dmvschool:pay", limit = 2},
    {name = "esx_truckerjob:pay", limit = 2},
    {name = "esx_gopostaljob:pay", limit = 2},
    {name = "esx_tankerjob:pay", limit = 2},
    {name = "esx_society:billing", limit = 2},
    {name = "esx_policejob:message", limit = 4},
    {name = "esx_truckerjob:pay", limit = 2},
    {name = "esx_gopostaljob:pay", limit = 2},
    {name = 'EasyAdmin:kickPlayer', limit = 4},
    {name = 'EasyAdmin:banPlayer', limit = 4},
    {name = 'EasyAdmin:offlinebanPlayer', limit = 4},
}

SVConfig.AntiFakeMessage = true
SVConfig.AntiMassParticles = true

SVConfig.ObjectWhitelist = {
    -1038739674,
    'p_till_01_s',
    'prop_poly_bag_01',
    'p_v_43_safe_s',
    'prop_box_wood02a_pu',
    'p_cargo_chute_s',
    'ex_prop_adv_case_sm',
    'prop_drug_package_02',
    'prop_tool_broom',
    'p_ld_stinger_s',
    'prop_monitor_w_large',
    'prop_rub_table_01',
    'xm_base_cia_server_01',
    'v_corp_servercln2',
    'prop_barrier_work05',
    'hei_prop_cash_crate_half_full',
    'prop_boxpile_07d',
    'prop_roadcone02a',
    'prop_wheelchair_01',
    'prop_ballistic_shield',
    'prop_cs_phone_01',
    'prop_money_bag_01',
    'prop_cs_spray_can',
    'w_ar_carbinerifle',
    'w_sg_pumpshotgun',
    'prop_v_cam_01',
    'p_ing_microphonel_01',
    'apa_mp_apa_yacht_jacuzzi_ripple1',
    'xm_prop_x17_l_door_glass_01',
    'xm_prop_x17_l_glass_01',
    'xm_prop_x17_l_glass_02',
    'xm_prop_x17_l_glass_03',
    'prop_cs_burger_01',
    'prop_peanut_bowl_01',
    'v_ret_ml_chips2',
    'prop_energy_drink',
    'prop_cs_beer_bot_02',
    'prop_cs_beer_bot_40oz_02',
    'p_whiskey_bottle_s',
    'prop_sh_tall_glass',
    'ba_prop_battle_shot_glass_01',
    'prop_mojito',
    'prop_rum_bottle',
    'v_res_fh_fruitbowl',
    'ng_proc_sodacan_01b',
    'prop_ld_flow_bottle',
    'vw_prop_vw_champ_closed',
    'prop_cs_coke_line',
    'prop_weed_bottle',
    'prop_cigar_03',
    'p_amb_joint_01',
    'prop_tool_pickaxe',
    'prop_cs_remote_01',
    'prop_cs_hand_radio',
    'prop_v_bmike_01',
    'hei_p_m_bag_var22_arm_s',
    'hei_prop_heist_thermite',
    'hei_prop_hst_laptop',
    'hei_prop_heist_card_hack_02',
    'p_ld_id_card_01',
    'hei_prop_heist_cash_pile',
    'prop_amb_phone',
    'ng_proc_sodabot_01a',
    'ng_proc_box_01a',
    'ng_proc_food_burg01a',
    'ba_prop_battle_glowstick_01',
    'ba_prop_battle_hobby_horse',
    'prop_rub_planks_01',
    'prop_log_01',
    'p_amb_brolly_01',
    'prop_notepad_01',
    'prop_pencil_01',
    'hei_prop_heist_box',
    'prop_single_rose',
    'prop_cs_ciggy_01',
    'hei_heist_sh_bong_01',
    'prop_police_id_board',
    'p_amb_coffeecup_01',
    'prop_drink_whisky',
    'prop_amb_beer_bottle',
    'prop_plastic_cup_02',
    'prop_amb_donut',
    'prop_sandwich_01',
    'prop_food_mustard',
    'prop_rolled_sock_02',
    'prop_ecola_can',
    'prop_boombox_01',
    'prop_choc_ego',
    'prop_drink_redwine',
    'prop_champ_flute',
    'prop_drink_champ',
    'prop_cigar_02',
    'prop_cigar_01',
    'prop_acc_guitar_01',
    'prop_el_guitar_01',
    'prop_el_guitar_03',
    'prop_novel_01',
    'prop_snow_flower_02',
    'v_ilev_mr_rasberryclean',
    'p_michael_backpack_s',
    'p_amb_clipboard_01',
    'prop_tourist_map_01',
    'prop_beggers_sign_03',
    'prop_anim_cash_pile_01',
    'prop_pap_camera_01',
    'ba_prop_battle_champ_open',
    'p_cs_joint_02',
    'prop_amb_ciggy_01',
    'prop_cs_tablet',
    'prop_npc_phone_02',
    'prop_sponge_01',
    'prop_cone_float_1',
    'prop_cctv_cam_01a_2',
    'prop_cctv_cam_01b_2',
    'prop_cctv_cam_02a_2',
    'prop_cctv_cam_03a_2',
    'prop_cctv_cam_04a_2',
    'prop_cctv_cam_04b_2',
    'prop_cctv_cam_04c_2',
    'prop_cctv_cam_05a_2',
    'prop_cctv_cam_06a_2',
    'prop_cctv_cam_07a_2',
    269934519,
    2007413986,
    881130828,
    769923921,
    2714348429
}

SVConfig.VehicleBlacklist = {
    "RHINO",
    "KHANJALI",
    "HUNTER",
    "CARGOBOB",
    "CARGOBOB2",
    "AIRBUS",
    "CARGOBOB3",
    "CARGOBOB4",
    "AKULA",
    "LUXOR",
    "SPARROW2",
    "CHERNOBOG",
    "THRUSTER",
    "MINITANK",
    "akula",
    "annihilator",
    "hunter",
    "savage",
    "cutter",
    "scarab3",
    "avenger",
    "avenger2",
    "cargoplane2",
    "cargoplane",
    "bombushka",
    "volatol",
    "alkonost",
    "submersible",
    "submersible2",
    "kosatka",
    "APC",
    "DUMP",
    "LAZER",
    "CARBUS",
    "JET",
    "HYDRA",
    "CARGOPLANE",
    "TITAN",
    "rhino",
    "apc",
    "hydra",
    "blimp",
    "blimp2",
    "blimp3",
    "avenger",
    "besra",
    "bombushka",
    "lazer",
    "strikeforce",
    "insurgent",
    "insurgent3",
    "insurgent2",
    "menacer",
    "dune4",
    "dune5",
    "caracara",
    "revolter",
    "barracks",
    "barracks2",
    "barracks3",
    "barrage",
    "chernobog",
    "crusader",
    "halftrack",
    "khanjali",
    "minitank",
    "scarab",
    "scarab2",
    "scarab3",
    "thruster",
    "trailersmall2",
    "vetir",
    "savage",
    "hunter",
    "akula",
    "buzzard",
    "annihilator",
    "riot2",
    "dinghy5",
    "kosatka",
    "patrolboat",
    "avisa",
    "submersible2",
    "submersible",
    "skylift",
    "bruiser3",
    "technical",
    "technical12",
    "technical13",
    "zhaba",
    "cutter",
    "dump",
    "cargoplane",
    "bruiser2",
    "valkyrie",
    "scramjet",
    "vigilante",
    "ZR380",
    "deluxo",
    "oppressor",
    "oppressor2",
    "shotaro",
    "cerberus",
    "brickade",
    "dune",
    "wastelander",
    "mogul",
    "alkonost",
    "tula",
    "volatol",
    "molotok",
    "Cargobob",
    "Nightshark",
    "Bruiser",
    "veto",
    "veto2",
    "tug",
    "ambulance",
}

SVConfig.PedBlacklist = {
    "a_c_dolphin",
    "a_c_killerwhale", 
    "a_c_sharktiger",
    "a_c_humpback",
    "mp_m_niko_01",
    "a_m_m_tramp_01",
    "hc_gunman",
    "ig_johnnyklebitz",
    "u_m_y_staggrm_01",
    'mp_m_marston_01',
    'u_m_y_prisoner_01',
    'ig_wade',
    'cs_orleans',
    's_m_y_swat_01',
    'mp_m_freemode_01',
    'mp_f_freemode_01',
    'a_m_y_skater_01',
    'u_m_y_pogo_01',
    "player_zero",
    "player_one",
    "player_two",
    "u_m_m_streetart_01",
    "u_m_m_jesus_01",
    "u_m_y_babyd",
    "u_m_y_rsranger_01",
    "u_m_y_zombie_01",
    "u_m_y_pogo_0",
    "s_m_y_clown_01",
    "s_m_m_movspace_01",
    "mp_f_cocaine_01",
    "g_m_y_famca_01",
    "g_m_y_ballasout_01",
    "g_m_y_famfor_01",
    "g_m_y_ballaeast_01",
    "a_c_chimp",
    "a_m_m_acult_01",
    "a_m_y_skater_02",
    "u_m_y_juggernaut_01",
    "a_c_chickenhawk",
    "a_c_crow",
    "a_c_cormorant",
    "a_c_seagull",
    "a_c_pigeon",
}

SVConfig.EventsRate = true
SVConfig.RateTimer = 3000
SVConfig.EventsRated = {
    {name = "asjkghfjhksafhjkasf:addContact", limit = 5},
    {name = "gcphone410255309243843843582193100974:updateContact", limit = 5},
    {name = "jakispiesek:siebawipl", limit = 5},
    {name = "gcphone410255309243843843582193100974:sendMessage", limit = 5},
    {name = "ashbjkfvavshjkfvhjkl2178t3412", limit = 2},
}
